Change launching of traci deamon and runScenario to be able to be done with parameters

diff --git a/launchSumoTraciDaemon b/launchSumoTraciDaemon
--- a/launchSumoTraciDaemon
+++ b/launchSumoTraciDaemon
@@ -10,23 +10,59 @@ if (echo >/dev/tcp/localhost/9999) &>/dev/null
         exit 1
 fi
 
-PS3='Please chose a configuration: '
-options_sim=("With GUI" "Without GUI" )
-select opt_sim in "${options_sim[@]}"
+POSITIONAL=()
+while [[ $# -gt 0 ]]
 do
-    case $opt_sim in
-        "With GUI")
-            echo "you chose choice $REPLY which is $opt_sim"
-            ./veins-f2md/sumo-launchd.py  -vv -c sumo-gui
-            break
-            ;;
-        "Without GUI")
-            echo "you chose choice $REPLY which is $opt_sim"
-            ./veins-f2md/sumo-launchd.py  -vv -c sumo
-            break
-            ;;
-        *) echo "invalid option $REPLY"
-            exit 1            
-            ;;
-    esac
+key="$1"
+case $key in
+    -g|--gui)
+    GUI="YES"
+    shift # past argument
+    ;;
+    -ng|--no-gui)
+    GUI="NO"
+    shift # past argument
+    ;;
+    *)    # unknown option
+    POSITIONAL+=("$1") # save it in an array for later
+    shift # past argument
+    ;;
+esac
 done
+set -- "${POSITIONAL[@]}" # restore positional parameters
+
+if [[ $GUI == "" ]]
+then
+    PS3='Please chose a configuration: '
+    options_sim=("With GUI" "Without GUI" )
+    select opt_sim in "${options_sim[@]}"
+    do
+        case $opt_sim in
+            "With GUI")
+                echo "you chose choice $REPLY which is $opt_sim"
+                GUI="YES"
+                break
+                ;;
+            "Without GUI")
+                echo "you chose choice $REPLY which is $opt_sim"
+                GUI="NO"
+                break
+                ;;
+            *) echo "invalid option $REPLY"
+                exit 1            
+                ;;
+        esac
+    done
+fi
+
+if [[ "${GUI}" == "YES" ]]
+then 
+    ./veins-f2md/sumo-launchd.py  -vv -c sumo-gui
+else
+    if [[ "${GUI}" == "NO" ]]
+    then
+        ./veins-f2md/sumo-launchd.py  -vv -c sumo
+    else
+        echo "Something went severely wrong"
+        exit 1
+fi
diff --git a/runScenario b/runScenario
--- a/runScenario
+++ b/runScenario
@@ -14,90 +14,185 @@ if [[ $portsinuse == *"9999"* ]]
         exit 1
 fi
 
-PS3='Please chose a scenario: '
-options_net=("IRTSystemXScenario" "LuSTNanoScenario" "LuSTMiniScenario" "LuSTScenario" "UlmScenario")
-select opt_net in "${options_net[@]}"
+POSITIONAL=()
+while [[ $# -gt 0 ]]
 do
-    case $opt_net in
-        "IRTSystemXScenario")
-            echo
-            echo "you chose choice $REPLY which is $opt_net"
-            break
-            ;;
-        "LuSTNanoScenario")
-            echo
-            echo "you chose choice $REPLY which is $opt_net"
-            break
-            ;;
-        "LuSTMiniScenario")
-            echo
-            echo "you chose choice $REPLY which is $opt_net"
-            break
-            ;;
-        "LuSTScenario")
-            echo
-            echo "you chose choice $REPLY which is $opt_net"
-            break
-            ;;
-        "UlmScenario")
-            echo
-            echo "you chose choice $REPLY which is $opt_net"
-            break
-            ;;
-        *) echo
-            echo "invalid option $REPLY"
-            exit 1            
-            ;;
-    esac
+key="$1"
+case $key in
+    -s|--scenario)
+    SCENARIO="$2"
+    shift # past argument
+    shift # past value
+    ;;
+    -t|--technology)
+    TECHNOLOGY="$2"
+    shift # past argument
+    shift # past value
+    ;;
+    -e|--env)
+    ENVIRONMENT="$2"
+    shift # past argument
+    shift # past value
+    ;;
+    *)    # unknown option
+    POSITIONAL+=("$1") # save it in an array for later
+    shift # past argument
+    ;;
+esac
 done
+set -- "${POSITIONAL[@]}" # restore positional parameters
+
+if [[ $SCENARIO == "" ]]
+then
+    PS3='Please chose a scenario: '
+    options_net=("IRTSystemXScenario" "LuSTNanoScenario" "LuSTMiniScenario" "LuSTScenario" "UlmScenario")
+    select opt_net in "${options_net[@]}"
+    do
+        case $opt_net in
+            "IRTSystemXScenario")
+                echo
+                echo "you chose choice $REPLY which is $opt_net"
+                break
+                ;;
+            "LuSTNanoScenario")
+                echo
+                echo "you chose choice $REPLY which is $opt_net"
+                break
+                ;;
+            "LuSTMiniScenario")
+                echo
+                echo "you chose choice $REPLY which is $opt_net"
+                break
+                ;;
+            "LuSTScenario")
+                echo
+                echo "you chose choice $REPLY which is $opt_net"
+                break
+                ;;
+            "UlmScenario")
+                echo
+                echo "you chose choice $REPLY which is $opt_net"
+                break
+                ;;
+            *) echo
+                echo "invalid option $REPLY"
+                exit 1            
+                ;;
+        esac
+    done
+else
+    if [[ $SCENARIO == "0" ]]
+    then
+        opt_net="IRTSystemXScenario"
+    else
+        if [[ $SCENARIO == "1" ]]
+        then
+            opt_net="LuSTNanoScenario"
+        else
+            if [[ $SCENARIO == "2" ]]
+            then
+                opt_net="LuSTMiniScenario"
+            else
+                if [[ $SCENARIO == "3" ]]
+                then
+                    opt_net="LuSTScenario"
+                else
+                    if [[ $SCENARIO == "4" ]]
+                    then
+                        opt_net="UlmScenario"
+                    else
+                        echo "Choose a valid scenario please (from 0 to 4)"
+                        exit 1
+                    fi 
+                fi
+            fi
+        fi
+    fi
+fi
+
 
 echo
-PS3='Please chose a technology: '
-options_tech=("ITS-G5 (IEEE 802.11p)" "C-V2X (3GPP PC5 Mode 4)" )
-select opt_tech in "${options_tech[@]}"
-do
-    case $opt_tech in
-        "ITS-G5 (IEEE 802.11p)")
-            echo
-            echo "you chose choice $REPLY which is $opt_tech"
-            cd "./veins-f2md/f2md-networks/"
-            break
-            ;;
-        "C-V2X (3GPP PC5 Mode 4)")
-            echo
-            opt_net="${opt_net}Mode4"
-            echo "you chose choice $REPLY which is $opt_tech"
-            cd "./simulte-f2md/f2md-networks/"
-            break
-            ;;
-        *) echo "invalid option $REPLY"
-            exit 1            
-            ;;
-    esac
-done
+
+if [[ $TECHNOLOGY == "" ]]
+then 
+    PS3='Please chose a technology: '
+    options_tech=("ITS-G5 (IEEE 802.11p)" "C-V2X (3GPP PC5 Mode 4)" )
+    select opt_tech in "${options_tech[@]}"
+    do
+        case $opt_tech in
+            "ITS-G5 (IEEE 802.11p)")
+                echo
+                echo "you chose choice $REPLY which is $opt_tech"
+                TECHNOLOGY="0"
+                break
+                ;;
+            "C-V2X (3GPP PC5 Mode 4)")
+                echo
+                echo "you chose choice $REPLY which is $opt_tech"
+                TECHNOLOGY="1"
+                break
+                ;;
+            *) echo "invalid option $REPLY"
+                exit 1            
+                ;;
+        esac
+    done
+fi
+
+if [[ $TECHNOLOGY == "0" ]]
+then
+    cd "./veins-f2md/f2md-networks/"
+else
+    if [[ $TECHNOLOGY == "1" ]]
+    then
+        opt_net="${opt_net}Mode4"
+        cd "./simulte-f2md/f2md-networks/"
+    else
+        echo "Invalid technology option (0 or 1)"
+        exit 1
+    fi
+fi
 echo
 
-PS3='Please chose a simulation environnement: '
-options_sim=("Cmdenv" "Qtenv" )
-select opt_sim in "${options_sim[@]}"
-do
-    case $opt_sim in
-        "Cmdenv")
-            echo
-            echo "you chose choice $REPLY which is $opt_sim"
-            break
-            ;;
-        "Qtenv")
-            echo
-            echo "you chose choice $REPLY which is $opt_sim"
-            break
-            ;;
-        *) echo 
-            echo "invalid option $REPLY"
-            exit 1            
-            ;;
-    esac
-done
+
+
+if [[ $ENVIRONMENT == "" ]]
+then 
+    PS3='Please chose a simulation environnement: '
+    options_sim=("Cmdenv" "Qtenv" )
+    select opt_sim in "${options_sim[@]}"
+    do
+        case $opt_sim in
+            "Cmdenv")
+                echo
+                echo "you chose choice $REPLY which is $opt_sim"
+                break
+                ;;
+            "Qtenv")
+                echo
+                echo "you chose choice $REPLY which is $opt_sim"
+                break
+                ;;
+            *) echo 
+                echo "invalid option $REPLY"
+                exit 1            
+                ;;
+        esac
+    done
+else
+    if [[ $ENVIRONMENT == "0" ]]
+    then
+        opt_sim="Cmdenv"
+    else
+        if [[ $ENVIRONMENT == "0" ]]
+        then
+            opt_sim="Qtenv"
+        else
+            echo "Please choose a valid environment option (0 or 1)"
+            exit 1
+        fi
+    fi
+fi
 
 cd $opt_net 
 ./run -u $opt_sim
