Added the right parameters to the complete run

diff --git a/sample b/sample
--- a/sample
+++ b/sample
@@ -7,11 +7,12 @@ HELP="$HELP $package [options]\n"
 HELP="$HELP \n"
 HELP="$HELP options:\n"
 HELP="$HELP -h,  --help                              show brief help\n"
-HELP="$HELP -s,  --scenario SCENARIO                 set this flag to automatically install sumo\n"
-HELP="$HELP -a,  --app-type APP_TYPE                 specify the version of sumo to install\n"
-HELP="$HELP -c,  --check-type CHECK_TYPE             set this flag to automatically install omnetpp\n"
+HELP="$HELP -s,  --scenario SCENARIO                 set this flag to determine the Scenario to use\n"
+HELP="$HELP -a,  --app-type APP_TYPE                 specify the app to detect misbehavior with\n"
+HELP="$HELP -c,  --check-type CHECK_TYPE             specify the type of plausibility detectors to use\n"
+HELP="$HELP -ad, --attacker-density ATTACKER_DENSITY set the attacker density of the model\n"
 HELP="$HELP -ml, --ml-type ML_TYPE                   specify the type of machine learning to be used if an\n"
-HELP="$HELP -sa,  --save-data SAVE_DATA               specify the version of omnetpp to install\n"
+HELP="$HELP -sa, --save-data SAVE_DATA               specify whether to save data or not from the machine learning model\n"
 
 POSITIONAL=()
 while [[ $# -gt 0 ]]
@@ -59,7 +60,7 @@ set -- "${POSITIONAL[@]}" # restore positional parameters
 
 if [[ $SCENARIO == "" ]]
 then
-    PS3='Please chose a scenario: '
+    PS3='Please choose a scenario: '
     options_net=("IRTSystemXScenario" "LuSTNanoScenario" "LuSTMiniScenario" "LuSTScenario" "UlmScenario")
     select opt_net in "${options_net[@]}"
     do
@@ -104,7 +105,7 @@ fi
 
 if [[ $APP_TYPE == "" ]]
 then
-    PS3='Please chose a app to be used for misbehavior detection: '
+    PS3='Please choose a app to be used for misbehavior detection: '
     options_app=("ThresholdApp" "AggregationApp" "BehavioralApp" "ExperiApp" "CooperativeApp" "MachineLearningApp")
     select opt_app in "${options_app[@]}"
     do
@@ -155,8 +156,40 @@ fi
 
 if [[ $CHECK_TYPE == "" ]]
 then
-    PS3='Please chose a type of plausibility detectors: '
+    PS3='Please choose a type of plausibility detectors: '
     options_check=("LegacyChecks" "CaTChChecks" "ExperiChecks")
+    select opt_check in "${options_check[@]}"
+    do
+        case $opt_check in
+            "LegacyChecks")
+                echo
+                echo "you chose choice $REPLY which is $opt_check"
+                CHECK_TYPE=1 
+                break
+                ;;
+            "CaTChChecks")
+                echo
+                echo "you chose choice $REPLY which is $opt_check"
+                CHECK_TYPE=2 
+                break
+                ;;
+            "ExperiChecks")
+                echo
+                echo "you chose choice $REPLY which is $opt_check"
+                CHECK_TYPE=3 
+                break
+                ;;
+            *) echo
+                echo "invalid option $REPLY"
+                exit 1            
+                ;;
+        esac
+    done
+fi
+
+if [[ $ATTACKER_DENSITY == "" ]]
+then
+    PS3='Please choose an attacker density (as percent number or float between 0 and 1): '
     select opt_check in "${options_check[@]}"
     do
         case $opt_check in
@@ -206,7 +239,7 @@ then
 else
     if [[ $ML_TYPE == "" ]]
     then
-        PS3='Please chose a type of ML algorithm: '
+        PS3='Please choose a type of ML algorithm: '
         options_ml=("SVM_SINGLE" "MLP_SINGLE_L1N25" "MLP_SINGLE_L3N25" "LSTM_RECURRENT")
         select opt_ml in "${options_ml[@]}"
         do
